"""empty message

Revision ID: 672ecc2dc53c
Revises: 76bb85a53feb
Create Date: 2022-10-13 17:19:53.858805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672ecc2dc53c'
down_revision = '76bb85a53feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'card', 'deck', ['deck_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    # ### end Alembic commands ###
