"""empty message

Revision ID: 76bb85a53feb
Revises: 
Create Date: 2022-10-13 12:26:05.200389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76bb85a53feb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'deck_id')
    )
    op.create_table('user',
    sa.Column('g_auth_uid', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('g_auth_uid')
    )
    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.g_auth_uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deck')
    op.drop_table('user')
    op.drop_table('card')
    # ### end Alembic commands ###
